name = "openmonetizationwallet"
type = "webpack"
workers_dev = true

kv-namespaces = [
  { binding = "DB", id = "7034d14022064bcebaa513cf027b295d" }
]

[site]
bucket = "./public"
entry-point = "workers-site"

[env.development]
kv-namespaces = [
  { binding = "DB", id = "7034d14022064bcebaa513cf027b295d" }
]

[env.production]
zone_id = "b6e4c59655bb1e7d3d49419fa667ae53"
route = "wallet.signalnerve.com/*"
kv-namespaces = [
  { binding = "DB", id = "7034d14022064bcebaa513cf027b295d" }
]
