# This wrangler.toml has been configured as an example of a production-ready
# wrangler.toml, and is also used to deploy the "demo" instance of OMW
# seen in the README/documentation.
#
# You should replace this with the contents of `wrangler.toml.example`:
#
# cp wrangler.toml.example wrangler.toml

name = "openmonetizationwallet-production"
type = "webpack"
workers_dev = false

zone_id = "b6e4c59655bb1e7d3d49419fa667ae53"
route = "wallet.signalnerve.com/*"
kv-namespaces = [
  { binding = "DB", id = "7034d14022064bcebaa513cf027b295d" }
]

[site]
bucket = "./public"
entry-point = "workers-site"

# Demo instance used for deploying example wallet
[env.demo]
name = "omw-demo"
workers_dev = true
vars = { DEMO = true }
kv-namespaces = [
  { binding = "DB", id = "2aedb635af274ff2806d60671719d58e" }
]
